/*
 * This Java source file was generated by the Gradle "init" task.
 */
package com.acme;

import java.util.Arrays;
import java.util.List;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.batch.AWSBatch;
import com.amazonaws.services.batch.AWSBatchClientBuilder;
import com.amazonaws.services.batch.model.ComputeResource;
import com.amazonaws.services.batch.model.CreateComputeEnvironmentRequest;
import com.amazonaws.services.batch.model.LaunchTemplateSpecification;

public class App {
    
    public void run() {

        String accessKey = System.getenv("AWS_ACCESS_KEY_ID");
        String secretKey = System.getenv("AWS_SECRET_ACCESS_KEY");
        
        AWSBatch client = AWSBatchClientBuilder
                .standard()
                .withRegion("eu-west-1")
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretKey) ))
                .build();

        ComputeResource res = new ComputeResource()
                .withType("EC2")
                .withMinvCpus(0)
                .withMaxvCpus(10)
                .withInstanceTypes(list("optimal"))
                .withImageId("ami-08803b8f0bf9db0ab")
                .withSubnets(list("subnet-baa90ce0", "subnet-0cbaadbbf7fe82ba1", "subnet-7c21b91a", "subnet-00aab8c8b2f4cfc91", "subnet-80a9c2c8"))
                .withSecurityGroupIds(list("sg-9f8be7e1"))
                .withInstanceRole("arn:aws:iam::195996028523:instance-profile/TowerForge-4IgIbmOvmsK3HX6ts4MPEh-InstanceRole")
                .withSpotIamFleetRole("arn:aws:iam::195996028523:role/TowerForge-4IgIbmOvmsK3HX6ts4MPEh-FleetRole")
                .withLaunchTemplate( new LaunchTemplateSpecification().withLaunchTemplateId("lt-02ca7bce3bb7a23e4") );

        CreateComputeEnvironmentRequest req = new CreateComputeEnvironmentRequest()
                .withComputeEnvironmentName("TowerForge-4IgIbmOvmsK3HX6ts4MPEh")
                .withType("MANAGED")
                .withServiceRole("arn:aws:iam::195996028523:role/TowerForge-4IgIbmOvmsK3HX6ts4MPEh-ServiceRole")
                .withComputeResources( res );

        client.createComputeEnvironment(req);
    }

    List<String> list(String ... items) {
        return Arrays.asList(items.clone());
    }

    public static void main(String[] args) {
        try {
            new App().run();
            System.out.println("Created!");
        }
        catch (Throwable e) {
            e.printStackTrace();
        }
    }
}
